### ISSUE TITLE
How to set use one GPU

### ISSUE THREAD

**Issue by tjusxh** [BVLC/caffe#1596]
When I training my data. I come across  segment error.I doubt imagenet use two GPU default.So I want to set one GPU. How to do it?

**Comment by santle** [comment]
To overcome the following error
F1219 15:59:41.175240 36602 common.cpp:137] Check failed: error == cudaSuccess (10 vs. 0) invalid device ordinal
please set the following parameter in the python code.
caffe.set_device(0)

**Comment by westeast** [comment]
I have the proble when i run :python examples/ssd/ssd_pascal.py  
I solve the problem by vim examples/ssd/ssd_pascal.py  modify   

 332 gpus = "0"

**Comment by dm02** [comment]
Check the file you are executing. There might be a value 'gpu = 0,1,2,3,4'. Change that to 'gpu = 0'

**Comment by Bardo91** [comment]
That solves the problem to me too

**Comment by ibeilinGX** [comment]
vim examples/ssd/ssd_pascal.py modify is really working for me

**Comment by zhixuanli** [comment]
If you are running `make runtest`, and encountered this problem,  
you can change the GPU id in `Makefile.config`.
Or you can try to run `export CUDA_VISIBLE_DEVICES=0` before you run the `make runtest`.
