### ISSUE TITLE
Cuda error in finetune the trained model: error == cudaSuccess (11 vs. 0) invalid argument

### ISSUE THREAD

**Issue by dreadlord1984** [BVLC/caffe#1749]
Env: ubuntu 14.04, caffe-0.99, Cuda toolkit 6.0,GTX-460
I have successfully trained or a model with 2500 classes.  
Then i want to finetune the trained model with 5000 classes (resume the 2500 classes model is also sucessful). So i modify the last output layer output classes whit new layer name, just as discribed in http://caffe.berkeleyvision.org/gathered/examples/finetune_flickr_style.html.
I have also successfully trianed a model with 5000 classes, with the same layer configure.

The model have 12 layers.
My error:

I0119 11:49:38.420044  3702 solver.cpp:426] Net size 12 param_id: 0 count: 1350 Src:0x501a29000 Dest:0x501a27a00
I0119 11:49:38.420121  3702 solver.cpp:426] Net size 12 param_id: 1 count: 150 Src:0x501922e00 Dest:0x501922a00
I0119 11:49:38.420413  3702 solver.cpp:426] Net size 12 param_id: 2 count: 150000 Src:0x509980000 Dest:0x508fa0000
I0119 11:49:38.420617  3702 solver.cpp:426] Net size 12 param_id: 3 count: 250 Src:0x501923200 Dest:0x501922600
I0119 11:49:38.421123  3702 solver.cpp:426] Net size 12 param_id: 4 count: 350000 Src:0x509a80000 Dest:0x508ae0000
I0119 11:49:38.421509  3702 solver.cpp:426] Net size 12 param_id: 5 count: 350 Src:0x503544c00 Dest:0x503544600
I0119 11:49:38.422535  3702 solver.cpp:426] Net size 12 param_id: 6 count: 630000 Src:0x509be0000 Dest:0x508760000
I0119 11:49:38.423049  3702 solver.cpp:426] Net size 12 param_id: 7 count: 450 Src:0x503545200 Dest:0x503543e00
I0119 11:49:38.425792  3702 solver.cpp:426] Net size 12 param_id: 8 count: 1800000 Src:0x509e60000 Dest:0x507f80000
I0119 11:49:38.426945  3702 solver.cpp:426] Net size 12 param_id: 9 count: 1000 Src:0x503545a00 Dest:0x503542e00
I0119 11:49:38.430330  3702 solver.cpp:426] Net size 12 param_id: 10 count: 5182000 Src:0x50a540000 Dest:0x506ba0000  (The different layer in finetune!!!)

F0119 11:49:38.430418  3702 math_functions.cpp:90] Check failed: error == cudaSuccess (11 vs. 0)  invalid argument
*** Check failure stack trace: ***
    @     0x7f9b1d5eddaa  (unknown)
    @     0x7f9b1d5edce4  (unknown)
    @     0x7f9b1d5ed6e6  (unknown)
    @     0x7f9b1d5f0687  (unknown)
    @           0x4b714a  caffe::caffe_copy<>()
    @           0x4a00c4  caffe::SGDSolver<>::ComputeUpdateValue()
    @           0x49b6d3  caffe::Solver<>::Solve()
    @           0x41046e  caffe::Solver<>::Solve()
    @           0x40de4d  train()
    @           0x40f508  main
    @     0x7f9b1a99aec5  (unknown)
    @           0x40d6e9  (unknown)
Aborted (core dumped)

I also found the caffe_copy() function have successfully execute, just aborted in the different layer.
The error of cuda in nvidia discribe like this "cudaErrorInvalidValue = 11, This indicates that one or more of the parameters passed to the API call is not within an acceptable range of values.", but i don't know what's wrong in my program. I just know little with cuda programming.

Any one can help me, or meet the same problem ? Thank you!

**Comment by erogol** [comment]
What is The compute capability of the gpu. Caffe recommends >2.0. I guess your problem is about tthe gpu capacity you use. Maybe it does not have enough thread blocks for The given net config. I experienced it and solved by changing data batch size.

**Comment by shelhamer** [comment]
Please ask hardware / CUDA questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list.

**Comment by dreadlord1984** [comment]
I have changed my the code version with caffe1.0 and cuda6.5. GTX460's compute capability = 2.0.
In the new env, the program run successfully.
I don't think there is the gpu compute capability problem, because the old env was successful in other training tasks. Maybe the caffe0.99 or the cuda6.0 have some problems.
