### ISSUE TITLE
crash with '-gpu=all'

### ISSUE THREAD

**Issue by cysin** [BVLC/caffe#3377]
I have encountered this error many times when enabling '-gpu=all'. I have two GPUs of 980 Ti and on CentOS 7 with cuda 7.5. I am also wondering has anyone succeeded with '-gpu=all' when training?

```
F1119 18:06:58.546988 14145 math_functions.cu:79] Check failed: error == cudaSuccess (4 vs. 0)  unspecified launch failure
*** Check failure stack trace: ***
    @     0x7f49be2e1e6d  (unknown)
    @     0x7f49be2e3ced  (unknown)
    @     0x7f49be2e1a5c  (unknown)
    @     0x7f49be2e463e  (unknown)
    @     0x7f49bf016834  caffe::caffe_gpu_memcpy()
    @     0x7f49bef7a30e  caffe::SyncedMemory::to_gpu()
    @     0x7f49bef797e9  caffe::SyncedMemory::gpu_data()
    @     0x7f49bee5fe12  caffe::Blob<>::gpu_data()
    @     0x7f49befec66f  caffe::InnerProductLayer<>::Forward_gpu()
    @     0x7f49befbdec1  caffe::Net<>::ForwardFromTo()
    @     0x7f49befbe247  caffe::Net<>::ForwardPrefilled()
    @     0x7f49bef5fad1  caffe::Solver<>::Step()
    @     0x7f49bef604d5  caffe::Solver<>::Solve()
    @     0x7f49befd80e5  caffe::P2PSync<>::run()
    @           0x40ab71  train()
    @           0x408881  main
    @     0x7f49b3ef3af5  __libc_start_main
    @           0x40903d  (unknown)
Aborted (core dumped)
```

**Comment by stoneljsh** [comment]
Is this problem solved? It happened to me as well.

**Comment by cysin** [comment]
It turned out to be the power issue. Be sure to have sufficient power, e.g. 1000w for two 980 Ti cards.

**Comment by stoneljsh** [comment]
@cysin , Thanks for sharing. I will try with stronger power.
