### ISSUE TITLE
Make all warnings leads to Make runtest fails

### ISSUE THREAD

**Issue by HAlmawi** [BVLC/caffe#3787]
Hi all,

I previously had cuda 7.5 installed and built opencv with it, however the version of caffe I'm using requires cuda 6.5 or previous versions. So I installed cuda 6.5, and reinstalled opencv and built it with cuda 6.5. However, I'm still getting the following warning:

/usr/bin/ld: warning: libcudart.so.7.5, needed by /usr/local/lib/libopencv_core.so, not found (try using -rpath or -rpath-link)

I did do "sudo ldconfig /usr/local/cuda-6.5/lib64" and also added "/home/halmawi/opencv-3.1.0/lib" (the newly compiled opencv with cuda 6.5) to my LD_LIBRARY_PATH.

Any ideas on how to fix this?

Thank you

**Comment by HAlmawi** [comment]
Problem fixed.

Solution: I downloaded OpenCV again, did the cmake (where it recognized cuda 6.5), and then create a soft link between the /usr/local/lib/libopencv_core.so with the newly installed OpenCV.

**Comment by linrio** [comment]
I happen the same problem with you.
`NVCC src/caffe/solvers/rmsprop_solver.cu
NVCC src/caffe/solvers/adam_solver.cu
AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so
CXX tools/test_net.cpp
CXX/LD -o .build_release/tools/test_net.bin
/usr/bin/ld: warning: libcudart.so.5.5, needed by /usr/local/lib/libopencv_core.so, may conflict with libcudart.so.6.0
`

I guess then version of cuda has problem. after $nvcc -V, 
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2013 NVIDIA Corporation
Built on Wed_Jul_17_18:36:13_PDT_2013
Cuda compilation tools, release 5.5, V5.5.0`

And I run $find cuda, it shows
`cuda: /usr/local/cuda` . In this file, it has `/usr/local/cuda/lib/libcudart.so.6.0`

in the LD_LIBRARY_PATH, I export the cuda-5.5.0 to it, but it still  throw out above problem, how to solve it?
