### ISSUE TITLE
set_mode(Caffe::CPU) is not respected during layer setup

### ISSUE THREAD

**Issue by gcp** [BVLC/caffe#3953]
C++ code:

    Caffe::set_mode(Caffe::CPU);

    net.reset(new Net<float>("model.txt", TEST));
    net->CopyTrainedLayersFrom("model.caffemodel");

This fails with:

F0406 15:16:18.456130 26296 cudnn_conv_layer.cpp:53] Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR
*** Check failure stack trace: ***
    @     0x7f14a890f778  (unknown)
    @     0x7f14a890f6b2  (unknown)
    @     0x7f14a890f0b4  (unknown)
    @     0x7f14a8912055  (unknown)
    @     0x7f14a901185f  caffe::CuDNNConvolutionLayer<>::LayerSetUp()
    @     0x7f14a90a645f  _ZN5caffe5LayerIfE5SetUpERKSt6vectorIPNS_4BlobIfEESaIS5_EES9_.localalias.423.lto_priv.1665
    @     0x7f14a90b92d9  _ZN5caffe3NetIfE4InitERKNS_12NetParameterE.localalias.410.lto_priv.2198
    @     0x7f14a90446ab  caffe::Net<>::Net()

CUDNN likely fails because another GPU user is already running. But when I set CPU mode, Caffe should not try to initialize GPU layers. (see CuDNNConvoluationLayer<>::LayerSetup() being called)

**Comment by ajtulloch** [comment]
Interesting. I guess the CuDNN layers call CUDA functions in LayerSetUp, regardless of Caffe::mode, and additionally there's no gating in [`caffe::GetConvolutionLayer`](https://github.com/BVLC/caffe/blob/843575eca2582fc30588ceaf31c987ad7707033d/src/caffe/layer_factory.cpp#L61) around Caffe::mode that controls what to load.

I guess adding a `Caffe::mode() == Caffe::GPU` around the CuDNN factory branches would work here, but maybe that's not desired.

**Comment by rddesmond** [comment]
This is a duplicate of https://github.com/BVLC/caffe/issues/3317.

**Comment by leoluopy** [comment]
my issue is solved by  adding "engine: CAFFE" in convolution_param
