### ISSUE TITLE
[opencl] Not detecting GPU

### ISSUE THREAD

**Issue by patmarks** [BVLC/caffe#4167]
I have an `ati radeon 6570 `with the latest catalyst driver and AMDAPPSDK-3.0 directly from AMD's website. The OS is debian, and I'm using opencv3 because I ran into some issues using opencv2 (dependency issue with libtiff4). `make all` was successful, except for a bunch of unused variable warnings. `runtest` works until running` test_all.testbin`, when I get the following:

```
Setting to use device 0
*** Aborted at 1463524769 (unix time) try "date -d @1463524769" if you are using GNU date ***
PC: @     0x7f95dd142dd1 caffe::Caffe::GetDevice()
*** SIGFPE (@0x7f95dd142dd1) received by PID 31254 (TID 0x7f95e2820a00) from PID 18446744073123671505; stack trace: ***
    @     0x7f95dc5278d0 (unknown)
    @     0x7f95dd142dd1 caffe::Caffe::GetDevice()
    @     0x7f95dd142e8a caffe::Caffe::SetDevices()
    @           0x4667a1 main
    @     0x7f95dc189b45 (unknown)
    @           0x46df89 (unknown)
    @                0x0 (unknown)
Floating point exception

```

clinfo [detects](https://gist.github.com/patmarks/888d96fbc0b92353e0d48c7dd3335a75) the GPU just fine, but running `caffe device_query` gives the following output:

```
I0517 17:50:52.262058  1825 common.cpp:371] Total devices: 0
I0517 17:50:52.262328  1825 common.cpp:372] CUDA devices: 0
I0517 17:50:52.262342  1825 common.cpp:373] OpenCL devices: 0
```
Or, I can get the same error that test_all.testbin gets by running  `caffe device_query -gpu 0`:

```
I0517 17:41:18.980022 31261 caffe.cpp:121] Querying GPUs 0
*** Aborted at 1463524878 (unix time) try "date -d @1463524878" if you are using GNU date ***
PC: @     0x7fbedbb22dd1 caffe::Caffe::GetDevice()
*** SIGFPE (@0x7fbedbb22dd1) received by PID 31261 (TID 0x7fbedbf9ea00) from PID 18446744073100471761; stack trace: ***
    @     0x7fbed5c9f8d0 (unknown)
    @     0x7fbedbb22dd1 caffe::Caffe::GetDevice()
    @     0x7fbedbb22e8a caffe::Caffe::SetDevices()
    @           0x407f63 device_query()
    @           0x405bb3 main
    @     0x7fbed5901b45 (unknown)
    @           0x40635c (unknown)
    @                0x0 (unknown)
Floating point exception

```
The CPU-only version compiles and runs OK. I was using the source from last week, but I just tried the opencl branch as of today, with the same results.

**Comment by naibaf7** [comment]
It seems like there is a libOpenCL.so present on the system that is not the correct one for your AMD chips.
This might help: http://computergraphics.stackexchange.com/questions/1990/opencl-doesnt-detect-gpu
Otherwise you can also try to just copy the libOpenCL.so found in your AMD APP SDK into /usr/lib64 and /usr/lib (or also /usr/lib32, depending on the OS). Then it should find the GPUs (you might need to recompile Caffe).

**Comment by patmarks** [comment]
@naibaf7, I don't think that's the case, since `clinfo` detected the GPU. I was also able to build and run this [toy example](https://github.com/smistad/OpenCL-Getting-Started/). 

However, I uninstalled AMDAPPSDK3.0 and downgraded to 2.9-1. I got the same errors, and `clinfo` still detected the GPU. 

Also, I do have the OpenCL libraries in LD_LIBRARY_PATH. I tried copying  libOpenCL.so into /usr/lib anyway, rebuilt, and got the same results.

**Comment by naibaf7** [comment]
@patmarks
Yeah if the toy example works, this should too.
Can I see your current Makefile.config?

**Comment by patmarks** [comment]
OK. I think I found the problem in the makefile. I forgot to enable greentea. Now that I have greentea enabled, the compilation fails during `make runtest` (caffe and test_all are not made). Here's [my makefile](https://gist.github.com/patmarks/fab2dc3c95e5c384a59349a317f36f28) (with greentea enabled this time).  And here's [the output](https://gist.github.com/patmarks/90a72d5427b7bf9d8a6cd6b633be7e6c) of make runtest. These are the last few lines, which I can't make heads or tails out of:

```
In file included from src/caffe/greentea/greentea_math_functions.cpp:44:0:
/usr/include/viennacl/linalg/prod.hpp:310:5: note: template<class StructuredMatrixType, class SCALARTYPE> typename viennacl::enable_if<viennacl::is_any_dense_structured_matrix<T>::value, viennacl::vector_expression<const SparseMatrixType, const viennacl::vector_base<NumericT>, viennacl::op_prod> >::type viennacl::linalg::prod(const StructuredMatrixType&, const viennacl::vector_base<NumericT>&)
     prod(const StructuredMatrixType & mat,
     ^
/usr/include/viennacl/linalg/prod.hpp:310:5: note:   template argument deduction/substitution failed:
/usr/include/viennacl/linalg/prod.hpp: In substitution of ‘template<class StructuredMatrixType, class SCALARTYPE> typename viennacl::enable_if<viennacl::is_any_dense_structured_matrix<T>::value, viennacl::vector_expression<const SparseMatrixType, const viennacl::vector_base<NumericT>, viennacl::op_prod> >::type viennacl::linalg::prod(const StructuredMatrixType&, const viennacl::vector_base<NumericT>&) [with StructuredMatrixType = viennacl::matrix_base<double, long unsigned int, long int, long int>; SCALARTYPE = double]’:
src/caffe/greentea/greentea_math_functions.cpp:457:51:   required from ‘void caffe::greentea_gpu_gemv(int32_t, CBLAS_TRANSPOSE, int32_t, int32_t, Dtype, cl_mem, int32_t, cl_mem, int32_t, Dtype, cl_mem, int32_t) [with Dtype = double; int32_t = int; cl_mem = _cl_mem*]’
src/caffe/greentea/greentea_math_functions.cpp:477:68:   required from here
/usr/include/viennacl/linalg/prod.hpp:310:5: error: no type named ‘type’ in ‘struct viennacl::enable_if<false, viennacl::vector_expression<const viennacl::matrix_base<double, long unsigned int, long int, long int>, const viennacl::vector_base<double>, viennacl::op_prod> >’
Makefile:692: recipe for target '.build_release/src/caffe/greentea/greentea_math_functions.o' failed
make: *** [.build_release/src/caffe/greentea/greentea_math_functions.o] Error 1
make: *** Waiting for unfinished jobs....

```

Is it a viennacl problem? I installed viennacl using apt-get.

**Comment by patmarks** [comment]
OK, partial success. For the record, I forgot to set the USE_GREENTEA flag, and was using viennacl 1.5.2 . Turning on the flag and switching to the latest viennacl from https://github.com/viennacl/viennacl-dev , I could successfully build and device_query sees the GPU.

**Comment by naibaf7** [comment]
@patmarks 
Great! I adapted the Makefile.config.example to be more "correct" by default. Otherwise just open up a new issue if you experience training or performance issues.
