### ISSUE TITLE
make test for ubuntu docker F0611 19:57:33.286557  4140 cudnn_softmax_layer.cpp:15] Check failed: status == CUDNN_STATUS_SUCCESS (1 vs. 0)  CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by martende** [BVLC/caffe#4291]
I am trying to start test on gpu docker container with installed cuda 7.5 and nvidia-docker 

this way, and receive test error

```
# nvidia-docker run --rm -ti caffe:gpu bash -c "cd /opt/caffe/build; make runtest"
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- Found lmdb    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/liblmdb.so)
-- Found LevelDB (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libleveldb.so)
-- Found Snappy  (include: /usr/include, library: /usr/lib/libsnappy.so)
-- CUDA detected: 7.5
-- Found cuDNN: ver. 5.0.5 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Added CUDA NVCC flags for: sm_50
-- OpenCV found (/usr/share/OpenCV)
-- Found Atlas (include: /usr/include, library: /usr/lib/libatlas.so)
-- NumPy ver. 1.8.2 found (include: /usr/lib/python2.7/dist-packages/numpy/core/include)
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   python
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- 
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0-rc3
--   Git               :   df412ac
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   ON
--   USE_LEVELDB       :   ON
--   USE_LMDB          :   ON
--   ALLOW_LMDB_NOLOCK :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.54)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 2.5.0)
--   lmdb              :   Yes (ver. 0.9.10)
--   LevelDB           :   Yes (ver. 1.15)
--   Snappy            :   Yes (ver. 1.1.0)
--   OpenCV            :   Yes (ver. 2.4.8)
--   CUDA              :   Yes (ver. 7.5)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_50
--   cuDNN             :   Yes (ver. 5.0.5)
-- 
-- Python:
--   Interpreter       :   /usr/bin/python2.7 (ver. 2.7.6)
--   Libraries         :   /usr/lib/x86_64-linux-gnu/libpython2.7.so (ver 2.7.6)
--   NumPy             :   /usr/lib/python2.7/dist-packages/numpy/core/include (ver 1.8.2)
-- 
-- Documentaion:
--   Doxygen           :   No
--   config_file       :   
-- 
-- Install:
--   Install path      :   /opt/caffe/build/install
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/caffe/build
[  1%] Built target proto
[  1%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/solvers/./cuda_compile_generated_rmsprop_solver.cu.o
[  1%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/solvers/./cuda_compile_generated_adagrad_solver.cu.o
[  2%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/solvers/./cuda_compile_generated_adam_solver.cu.o
[  2%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/solvers/./cuda_compile_generated_adadelta_solver.cu.o
[  2%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/solvers/./cuda_compile_generated_sgd_solver.cu.o
[  3%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/solvers/./cuda_compile_generated_nesterov_solver.cu.o
[  3%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_im2col.cu.o
[  4%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_math_functions.cu.o
[  4%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_absval_layer.cu.o
[  4%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_bias_layer.cu.o
[  5%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_inner_product_layer.cu.o
[  5%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_split_layer.cu.o
[  6%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_crop_layer.cu.o
[  6%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_cudnn_conv_layer.cu.o
[  6%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_eltwise_layer.cu.o
[  7%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_lrn_layer.cu.o
[  7%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_contrastive_loss_layer.cu.o
[  8%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_cudnn_tanh_layer.cu.o
[  8%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_sigmoid_cross_entropy_loss_layer.cu.o
[  8%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_prelu_layer.cu.o
[  9%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_scale_layer.cu.o
[  9%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_silence_layer.cu.o
[ 10%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_exp_layer.cu.o
[ 10%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_cudnn_lcn_layer.cu.o
[ 10%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_mvn_layer.cu.o
[ 11%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_hdf5_data_layer.cu.o
[ 11%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_threshold_layer.cu.o
[ 12%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_embed_layer.cu.o
[ 12%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_tile_layer.cu.o
[ 12%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_cudnn_softmax_layer.cu.o
[ 13%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_log_layer.cu.o
[ 13%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_cudnn_relu_layer.cu.o
[ 15%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_deconv_layer.cu.o
[ 15%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_lstm_unit_layer.cu.o
[ 15%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_reduction_layer.cu.o
[ 16%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_euclidean_loss_layer.cu.o
[ 16%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_tanh_layer.cu.o
[ 17%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_cudnn_sigmoid_layer.cu.o
[ 17%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_recurrent_layer.cu.o
[ 17%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_conv_layer.cu.o
[ 18%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_pooling_layer.cu.o
[ 18%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_batch_norm_layer.cu.o
[ 19%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_filter_layer.cu.o
[ 19%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_softmax_loss_layer.cu.o
[ 19%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_concat_layer.cu.o
[ 20%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_slice_layer.cu.o
[ 20%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_hdf5_output_layer.cu.o
[ 21%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_elu_layer.cu.o
[ 21%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_sigmoid_layer.cu.o
[ 21%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_bnll_layer.cu.o
[ 22%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_softmax_layer.cu.o
[ 22%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_dropout_layer.cu.o
[ 23%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_relu_layer.cu.o
[ 23%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_base_data_layer.cu.o
[ 23%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_power_layer.cu.o
[ 24%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_im2col_layer.cu.o
[ 24%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_cudnn_lrn_layer.cu.o
[ 25%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_batch_reindex_layer.cu.o
[ 25%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_cudnn_pooling_layer.cu.o
Scanning dependencies of target caffe
Linking CXX shared library ../../lib/libcaffe.so
[ 69%] Built target caffe
Scanning dependencies of target gtest
[ 69%] Building CXX object src/gtest/CMakeFiles/gtest.dir/gtest-all.cpp.o
Linking CXX static library ../../lib/libgtest.a
[ 69%] Built target gtest
[ 69%] Building NVCC (Device) object src/caffe/test/CMakeFiles/cuda_compile.dir//./cuda_compile_generated_test_im2col_kernel.cu.o
Scanning dependencies of target test.testbin
[ 70%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_infogain_loss_layer.cpp.o
[ 70%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_math_functions.cpp.o
[ 72%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_lstm_layer.cpp.o
[ 72%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_lrn_layer.cpp.o
[ 72%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_im2col_layer.cpp.o
[ 73%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_convolution_layer.cpp.o
[ 73%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_data_transformer.cpp.o
[ 74%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_solver_factory.cpp.o
[ 74%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_split_layer.cpp.o
[ 74%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_bias_layer.cpp.o
[ 75%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_layer_factory.cpp.o
[ 75%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_softmax_with_loss_layer.cpp.o
[ 76%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_scale_layer.cpp.o
[ 76%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_syncedmem.cpp.o
[ 76%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_spp_layer.cpp.o
[ 77%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_filler.cpp.o
[ 77%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_slice_layer.cpp.o
[ 78%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_tanh_layer.cpp.o
[ 78%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_blob.cpp.o
[ 78%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_reshape_layer.cpp.o
[ 79%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_internal_thread.cpp.o
[ 79%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_argmax_layer.cpp.o
[ 80%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_filter_layer.cpp.o
[ 80%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_concat_layer.cpp.o
[ 80%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_image_data_layer.cpp.o
[ 81%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_batch_norm_layer.cpp.o
[ 81%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_eltwise_layer.cpp.o
[ 82%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_platform.cpp.o
[ 82%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_contrastive_loss_layer.cpp.o
[ 82%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_db.cpp.o
[ 83%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_rnn_layer.cpp.o
[ 83%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_deconvolution_layer.cpp.o
[ 84%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_tile_layer.cpp.o
[ 84%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_upgrade_proto.cpp.o
[ 84%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_sigmoid_cross_entropy_loss_layer.cpp.o
[ 86%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_mvn_layer.cpp.o
[ 86%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_pooling_layer.cpp.o
[ 87%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_hdf5_output_layer.cpp.o
[ 87%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_maxpool_dropout_layers.cpp.o
[ 87%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_common.cpp.o
[ 88%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_memory_data_layer.cpp.o
[ 88%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_crop_layer.cpp.o
[ 89%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_stochastic_pooling.cpp.o
[ 89%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_solver.cpp.o
[ 89%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_batch_reindex_layer.cpp.o
[ 90%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_softmax_layer.cpp.o
[ 90%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_power_layer.cpp.o
[ 91%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_net.cpp.o
[ 91%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_util_blas.cpp.o
[ 91%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_benchmark.cpp.o
[ 92%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_hdf5data_layer.cpp.o
[ 92%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_multinomial_logistic_loss_layer.cpp.o
[ 93%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_io.cpp.o
[ 93%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_inner_product_layer.cpp.o
[ 93%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_reduction_layer.cpp.o
[ 94%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_caffe_main.cpp.o
[ 94%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_embed_layer.cpp.o
[ 95%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_data_layer.cpp.o
[ 95%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_hinge_loss_layer.cpp.o
[ 95%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_euclidean_loss_layer.cpp.o
[ 96%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_protobuf.cpp.o
[ 96%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_accuracy_layer.cpp.o
[ 97%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_flatten_layer.cpp.o
[ 97%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_threshold_layer.cpp.o
[ 97%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_neuron_layer.cpp.o
[ 98%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_gradient_based_solver.cpp.o
[ 98%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_dummy_data_layer.cpp.o
[100%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_random_number_generator.cpp.o
Linking CXX executable ../../../test/test.testbin
[100%] Built target test.testbin
Scanning dependencies of target runtest
libdc1394 error: Failed to initialize libdc1394
Cuda number of devices: 1
Current device id: 0
Current device name: GeForce GTX 745
Note: Randomizing tests' orders with a seed of 85010 .
[==========] Running 2069 tests from 277 test cases.
[----------] Global test environment set-up.
[----------] 9 tests from AdaGradSolverTest/1, where TypeParam = caffe::CPUDevice<double>
[ RUN      ] AdaGradSolverTest/1.TestAdaGradLeastSquaresUpdateLROneHundredth
[       OK ] AdaGradSolverTest/1.TestAdaGradLeastSquaresUpdateLROneHundredth (1158 ms)
[ RUN      ] AdaGradSolverTest/1.TestAdaGradLeastSquaresUpdateWithWeightDecay
[       OK ] AdaGradSolverTest/1.TestAdaGradLeastSquaresUpdateWithWeightDecay (5 ms)
[ RUN      ] AdaGradSolverTest/1.TestAdaGradLeastSquaresUpdateWithEverything
[       OK ] AdaGradSolverTest/1.TestAdaGradLeastSquaresUpdateWithEverything (26 ms)
[ RUN      ] AdaGradSolverTest/1.TestLeastSquaresUpdateWithEverythingAccum
[       OK ] AdaGradSolverTest/1.TestLeastSquaresUpdateWithEverythingAccum (1 ms)
[ RUN      ] AdaGradSolverTest/1.TestSnapshot
[       OK ] AdaGradSolverTest/1.TestSnapshot (9 ms)
[ RUN      ] AdaGradSolverTest/1.TestLeastSquaresUpdateWithEverythingAccumShare
[       OK ] AdaGradSolverTest/1.TestLeastSquaresUpdateWithEverythingAccumShare (3 ms)
[ RUN      ] AdaGradSolverTest/1.TestAdaGradLeastSquaresUpdateWithEverythingShare
[       OK ] AdaGradSolverTest/1.TestAdaGradLeastSquaresUpdateWithEverythingShare (28 ms)
[ RUN      ] AdaGradSolverTest/1.TestAdaGradLeastSquaresUpdate
[       OK ] AdaGradSolverTest/1.TestAdaGradLeastSquaresUpdate (5 ms)
[ RUN      ] AdaGradSolverTest/1.TestSnapshotShare
[       OK ] AdaGradSolverTest/1.TestSnapshotShare (13 ms)
[----------] 9 tests from AdaGradSolverTest/1 (1248 ms total)

[----------] 5 tests from EmbedLayerTest/0, where TypeParam = caffe::CPUDevice<float>
[ RUN      ] EmbedLayerTest/0.TestGradient
[       OK ] EmbedLayerTest/0.TestGradient (9 ms)
[ RUN      ] EmbedLayerTest/0.TestSetUp
[       OK ] EmbedLayerTest/0.TestSetUp (0 ms)
[ RUN      ] EmbedLayerTest/0.TestGradientWithBias
[       OK ] EmbedLayerTest/0.TestGradientWithBias (20 ms)
[ RUN      ] EmbedLayerTest/0.TestForwardWithBias
[       OK ] EmbedLayerTest/0.TestForwardWithBias (0 ms)
[ RUN      ] EmbedLayerTest/0.TestForward
[       OK ] EmbedLayerTest/0.TestForward (0 ms)
[----------] 5 tests from EmbedLayerTest/0 (29 ms total)

[----------] 5 tests from BlobSimpleTest/1, where TypeParam = double
[ RUN      ] BlobSimpleTest/1.TestLegacyBlobProtoShapeEquals
[       OK ] BlobSimpleTest/1.TestLegacyBlobProtoShapeEquals (0 ms)
[ RUN      ] BlobSimpleTest/1.TestReshapeZero
[       OK ] BlobSimpleTest/1.TestReshapeZero (0 ms)
[ RUN      ] BlobSimpleTest/1.TestReshape
[       OK ] BlobSimpleTest/1.TestReshape (0 ms)
[ RUN      ] BlobSimpleTest/1.TestPointersCPUGPU
[       OK ] BlobSimpleTest/1.TestPointersCPUGPU (7 ms)
[ RUN      ] BlobSimpleTest/1.TestInitialization
[       OK ] BlobSimpleTest/1.TestInitialization (0 ms)
[----------] 5 tests from BlobSimpleTest/1 (7 ms total)

[----------] 7 tests from CPUMathFunctionsTest/1, where TypeParam = double
[ RUN      ] CPUMathFunctionsTest/1.TestAsum
[       OK ] CPUMathFunctionsTest/1.TestAsum (10 ms)
[ RUN      ] CPUMathFunctionsTest/1.TestSign
[       OK ] CPUMathFunctionsTest/1.TestSign (9 ms)
[ RUN      ] CPUMathFunctionsTest/1.TestFabs
[       OK ] CPUMathFunctionsTest/1.TestFabs (10 ms)
[ RUN      ] CPUMathFunctionsTest/1.TestScale
[       OK ] CPUMathFunctionsTest/1.TestScale (10 ms)
[ RUN      ] CPUMathFunctionsTest/1.TestSgnbit
[       OK ] CPUMathFunctionsTest/1.TestSgnbit (9 ms)
[ RUN      ] CPUMathFunctionsTest/1.TestNothing
[       OK ] CPUMathFunctionsTest/1.TestNothing (9 ms)
[ RUN      ] CPUMathFunctionsTest/1.TestCopy
[       OK ] CPUMathFunctionsTest/1.TestCopy (8 ms)
[----------] 7 tests from CPUMathFunctionsTest/1 (66 ms total)

[----------] 3 tests from MSRAFillerTest/0, where TypeParam = float
[ RUN      ] MSRAFillerTest/0.TestFillFanIn
[       OK ] MSRAFillerTest/0.TestFillFanIn (0 ms)
[ RUN      ] MSRAFillerTest/0.TestFillFanOut
[       OK ] MSRAFillerTest/0.TestFillFanOut (1 ms)
[ RUN      ] MSRAFillerTest/0.TestFillAverage
[       OK ] MSRAFillerTest/0.TestFillAverage (1 ms)
[----------] 3 tests from MSRAFillerTest/0 (2 ms total)

[----------] 11 tests from CropLayerTest/3, where TypeParam = caffe::GPUDevice<double>
[ RUN      ] CropLayerTest/3.TestDimensionsCheck
[       OK ] CropLayerTest/3.TestDimensionsCheck (2 ms)
[ RUN      ] CropLayerTest/3.TestCropAllOffset
[       OK ] CropLayerTest/3.TestCropAllOffset (2 ms)
[ RUN      ] CropLayerTest/3.TestCropAllGradient
[       OK ] CropLayerTest/3.TestCropAllGradient (1083 ms)
[ RUN      ] CropLayerTest/3.TestCropHWGradient
[       OK ] CropLayerTest/3.TestCropHWGradient (1688 ms)
[ RUN      ] CropLayerTest/3.TestSetupShapeAll
[       OK ] CropLayerTest/3.TestSetupShapeAll (1 ms)
[ RUN      ] CropLayerTest/3.TestCropAll
[       OK ] CropLayerTest/3.TestCropAll (2 ms)
[ RUN      ] CropLayerTest/3.TestSetupShapeDefault
[       OK ] CropLayerTest/3.TestSetupShapeDefault (1 ms)
[ RUN      ] CropLayerTest/3.TestCrop5DGradient
[       OK ] CropLayerTest/3.TestCrop5DGradient (8564 ms)
[ RUN      ] CropLayerTest/3.TestCrop5D
[       OK ] CropLayerTest/3.TestCrop5D (3 ms)
[ RUN      ] CropLayerTest/3.TestSetupShapeNegativeIndexing
[       OK ] CropLayerTest/3.TestSetupShapeNegativeIndexing (1 ms)
[ RUN      ] CropLayerTest/3.TestCropHW
[       OK ] CropLayerTest/3.TestCropHW (2 ms)
[----------] 11 tests from CropLayerTest/3 (11349 ms total)

[----------] 15 tests from ConvolutionLayerTest/3, where TypeParam = caffe::GPUDevice<double>
[ RUN      ] ConvolutionLayerTest/3.TestSimpleConvolution
[       OK ] ConvolutionLayerTest/3.TestSimpleConvolution (2 ms)
[ RUN      ] ConvolutionLayerTest/3.TestDilated3DConvolution
[       OK ] ConvolutionLayerTest/3.TestDilated3DConvolution (11 ms)
[ RUN      ] ConvolutionLayerTest/3.Test0DConvolution
[       OK ] ConvolutionLayerTest/3.Test0DConvolution (2 ms)
[ RUN      ] ConvolutionLayerTest/3.TestSetup
[       OK ] ConvolutionLayerTest/3.TestSetup (1 ms)
[ RUN      ] ConvolutionLayerTest/3.TestSobelConvolution
[       OK ] ConvolutionLayerTest/3.TestSobelConvolution (2 ms)
[ RUN      ] ConvolutionLayerTest/3.TestGradient
[       OK ] ConvolutionLayerTest/3.TestGradient (1533 ms)
[ RUN      ] ConvolutionLayerTest/3.TestSimpleConvolutionGroup
[       OK ] ConvolutionLayerTest/3.TestSimpleConvolutionGroup (2 ms)
[ RUN      ] ConvolutionLayerTest/3.TestGradient3D
[       OK ] ConvolutionLayerTest/3.TestGradient3D (5313 ms)
[ RUN      ] ConvolutionLayerTest/3.TestDilatedConvolution
[       OK ] ConvolutionLayerTest/3.TestDilatedConvolution (3 ms)
[ RUN      ] ConvolutionLayerTest/3.Test1x1Gradient
[       OK ] ConvolutionLayerTest/3.Test1x1Gradient (10253 ms)
[ RUN      ] ConvolutionLayerTest/3.TestNDAgainst2D
[       OK ] ConvolutionLayerTest/3.TestNDAgainst2D (133 ms)
[ RUN      ] ConvolutionLayerTest/3.TestGradientGroup
[       OK ] ConvolutionLayerTest/3.TestGradientGroup (466 ms)
[ RUN      ] ConvolutionLayerTest/3.TestDilatedGradient
[       OK ] ConvolutionLayerTest/3.TestDilatedGradient (341 ms)
[ RUN      ] ConvolutionLayerTest/3.Test1x1Convolution
[       OK ] ConvolutionLayerTest/3.Test1x1Convolution (1 ms)
[ RUN      ] ConvolutionLayerTest/3.TestSimple3DConvolution
[       OK ] ConvolutionLayerTest/3.TestSimple3DConvolution (4 ms)
[----------] 15 tests from ConvolutionLayerTest/3 (18071 ms total)

[----------] 5 tests from ImageDataLayerTest/2, where TypeParam = caffe::GPUDevice<float>
[ RUN      ] ImageDataLayerTest/2.TestResize
[       OK ] ImageDataLayerTest/2.TestResize (125 ms)
[ RUN      ] ImageDataLayerTest/2.TestShuffle
[       OK ] ImageDataLayerTest/2.TestShuffle (90 ms)
[ RUN      ] ImageDataLayerTest/2.TestSpace
[       OK ] ImageDataLayerTest/2.TestSpace (28 ms)
[ RUN      ] ImageDataLayerTest/2.TestRead
[       OK ] ImageDataLayerTest/2.TestRead (89 ms)
[ RUN      ] ImageDataLayerTest/2.TestReshape
[       OK ] ImageDataLayerTest/2.TestReshape (26 ms)
[----------] 5 tests from ImageDataLayerTest/2 (358 ms total)

[----------] 8 tests from RMSPropSolverTest/0, where TypeParam = caffe::CPUDevice<float>
[ RUN      ] RMSPropSolverTest/0.TestRMSPropLeastSquaresUpdateWithWeightDecay
[       OK ] RMSPropSolverTest/0.TestRMSPropLeastSquaresUpdateWithWeightDecay (8 ms)
[ RUN      ] RMSPropSolverTest/0.TestRMSPropLeastSquaresUpdateWithEverything
[       OK ] RMSPropSolverTest/0.TestRMSPropLeastSquaresUpdateWithEverything (28 ms)
[ RUN      ] RMSPropSolverTest/0.TestLeastSquaresUpdateWithEverythingAccum
[       OK ] RMSPropSolverTest/0.TestLeastSquaresUpdateWithEverythingAccum (2 ms)
[ RUN      ] RMSPropSolverTest/0.TestSnapshot
[       OK ] RMSPropSolverTest/0.TestSnapshot (9 ms)
[ RUN      ] RMSPropSolverTest/0.TestRMSPropLeastSquaresUpdateWithRmsDecay
[       OK ] RMSPropSolverTest/0.TestRMSPropLeastSquaresUpdateWithRmsDecay (28 ms)
[ RUN      ] RMSPropSolverTest/0.TestLeastSquaresUpdateWithEverythingAccumShare
[       OK ] RMSPropSolverTest/0.TestLeastSquaresUpdateWithEverythingAccumShare (2 ms)
[ RUN      ] RMSPropSolverTest/0.TestSnapshotShare
[       OK ] RMSPropSolverTest/0.TestSnapshotShare (12 ms)
[ RUN      ] RMSPropSolverTest/0.TestRMSPropLeastSquaresUpdateWithEverythingShare
[       OK ] RMSPropSolverTest/0.TestRMSPropLeastSquaresUpdateWithEverythingShare (31 ms)
[----------] 8 tests from RMSPropSolverTest/0 (120 ms total)

[----------] 1 test from CPUStochasticPoolingLayerTest/1, where TypeParam = double
[ RUN      ] CPUStochasticPoolingLayerTest/1.TestSetup
[       OK ] CPUStochasticPoolingLayerTest/1.TestSetup (0 ms)
[----------] 1 test from CPUStochasticPoolingLayerTest/1 (0 ms total)

[----------] 23 tests from NetTest/0, where TypeParam = caffe::CPUDevice<float>
[ RUN      ] NetTest/0.TestGetBlob
F0611 19:57:33.286557  4140 cudnn_softmax_layer.cpp:15] Check failed: status == CUDNN_STATUS_SUCCESS (1 vs. 0)  CUDNN_STATUS_NOT_INITIALIZED
*** Check failure stack trace: ***
    @     0x2af5f9cbedaa  (unknown)
    @     0x2af5f9cbece4  (unknown)
    @     0x2af5f9cbe6e6  (unknown)
    @     0x2af5f9cc1687  (unknown)
    @     0x2af5f8f0be0b  caffe::CuDNNSoftmaxLayer<>::LayerSetUp()
    @     0x2af5f8f65647  caffe::SoftmaxWithLossLayer<>::LayerSetUp()
    @     0x2af5f8fd69e5  caffe::Net<>::Init()
    @     0x2af5f8fd7885  caffe::Net<>::Net()
    @           0xbfc64b  caffe::NetTest<>::InitNetFromProtoString()
    @           0xbbaffc  caffe::NetTest<>::InitTinyNet()
    @           0xbf78ea  caffe::NetTest_TestGetBlob_Test<>::TestBody()
    @           0xd87f63  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0xd7e9e7  testing::Test::Run()
    @           0xd7ea8e  testing::TestInfo::Run()
    @           0xd7eb95  testing::TestCase::Run()
    @           0xd818e8  testing::internal::UnitTestImpl::RunAllTests()
    @           0xd81b87  testing::UnitTest::Run()
    @           0x88f50f  main
    @     0x2af5ff49df45  (unknown)
    @           0x891622  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)
make[3]: *** [src/caffe/test/CMakeFiles/runtest] Error 134
make[2]: *** [src/caffe/test/CMakeFiles/runtest.dir/all] Error 2
make[1]: *** [src/caffe/test/CMakeFiles/runtest.dir/rule] Error 2
make: *** [runtest] Error 2
](url)
```

**Comment by ajtulloch** [comment]
This indicates a CuDNN/CUDA error. I've seen this when the CUDA/driver version and the CuDNN version are mismatched (5.0.5 and CUDA 7.0). This is almost certainly something to do with your setup, and not a bug in Caffe.

**Comment by martende** [comment]
I think that you are right - its configuration problem. But I have not installed cudnn at all - I am using docker container from https://github.com/BVLC/caffe/tree/master/docker and try to make connection with my host nvidia-driver . 

I have installed cuda-7.5 on host machine and nvidia-docker .

pacakges in docker are :

```
root@4f0e45b1c6e3:/workspace# dpkg -l | grep cud
ii  cuda-command-line-tools-7-5            7.5-18                                     amd64        CUDA command-line tools
ii  cuda-core-7-5                          7.5-18                                     amd64        CUDA core tools
ii  cuda-cublas-7-5                        7.5-18                                     amd64        CUBLAS native runtime libraries
ii  cuda-cublas-dev-7-5                    7.5-18                                     amd64        CUBLAS native dev links, headers
ii  cuda-cudart-7-5                        7.5-18                                     amd64        CUDA Runtime native Libraries
ii  cuda-cudart-dev-7-5                    7.5-18                                     amd64        CUDA Runtime native dev links, headers
ii  cuda-cufft-7-5                         7.5-18                                     amd64        CUFFT native runtime libraries
ii  cuda-cufft-dev-7-5                     7.5-18                                     amd64        CUFFT native dev links, headers
ii  cuda-curand-7-5                        7.5-18                                     amd64        CURAND native runtime libraries
ii  cuda-curand-dev-7-5                    7.5-18                                     amd64        CURAND native dev links, headers
ii  cuda-cusolver-7-5                      7.5-18                                     amd64        CUDA solver native runtime libraries
ii  cuda-cusolver-dev-7-5                  7.5-18                                     amd64        CUDA solver native dev links, headers
ii  cuda-cusparse-7-5                      7.5-18                                     amd64        CUSPARSE native runtime libraries
ii  cuda-cusparse-dev-7-5                  7.5-18                                     amd64        CUSPARSE native dev links, headers
ii  cuda-driver-dev-7-5                    7.5-18                                     amd64        CUDA Driver native dev stub library
ii  cuda-license-7-5                       7.5-18                                     amd64        CUDA licenses
ii  cuda-misc-headers-7-5                  7.5-18                                     amd64        CUDA misc headers
ii  cuda-npp-7-5                           7.5-18                                     amd64        NPP native runtime libraries
ii  cuda-npp-dev-7-5                       7.5-18                                     amd64        NPP native dev links, headers
ii  cuda-nvrtc-7-5                         7.5-18                                     amd64        NVRTC native runtime libraries
ii  cuda-nvrtc-dev-7-5                     7.5-18                                     amd64        NVRTC native dev links, headers
ii  libcudnn5                              5.0.5-1+cuda8.0                            amd64        cuDNN runtime libraries
ii  libcudnn5-dev                          5.0.5-1+cuda7.5                            amd64        cuDNN development libraries and headers
root@4f0e45b1c6e3:/workspace# 

```

**Comment by martende** [comment]
> I'd suggest printing out all your CUDA version, driver version (nvidia-smi), and CuDNN version (e.g. 5.0.5), and make sure that the sample CuDNN programs that are distributed with CuDNN work correctly.

```

Sun Jun 12 13:10:41 2016       
+------------------------------------------------------+                       
| NVIDIA-SMI 352.63     Driver Version: 352.63         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 745     Off  | 0000:01:00.0      On |                  N/A |
| 20%   43C    P8    N/A /  N/A |    258MiB /  4092MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0       911    G   /usr/bin/X                                     107MiB |
|    0      1993    G   compiz                                          75MiB |
+-----------------------------------------------------------------------------+

```

and in docker:

Sun Jun 12 11:11:40 2016       
+------------------------------------------------------+                       
| NVIDIA-SMI 352.63     Driver Version: 352.63         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 745     Off  | 0000:01:00.0      On |                  N/A |
| 20%   44C    P8    N/A /  N/A |    257MiB /  4092MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

**Comment by windywinter** [comment]
I encountered the same issue and finally found out that there is a mysterious
ii  libcudnn5                              5.0.5-1+**cuda8.0**                            amd64        cuDNN runtime libraries
in nvidia's cudnn image.
I haven't figure out where it come from yet, but I was able to solve the problem by removing it and installing the correct one.

**Comment by ajtulloch** [comment]
```
ii  libcudnn5                              5.0.5-1+cuda8.0                            amd64        cuDNN runtime libraries
ii  libcudnn5-dev                          5.0.5-1+cuda7.5                            amd64        cuDNN development libraries and headers
```

That looks like a potential issue.

**Comment by martende** [comment]
@windywinter :+1 - i have done the same. and the problem was solved.
