### ISSUE TITLE
CUDA invalid device ordinal

### ISSUE THREAD

**Issue by AlexTS1980** [BVLC/caffe#4894]
I've installed CUDA and Caffe without errors. While running [code]make runtest[/code] in caffe source dir, I keep getting [code]Check failed: error == cudaSuccess (10 vs. 0)  invalid device ordinal[/code] error. After running ./deviceQuery in cuda directory, I got a very similar error:

```
cudaGetDeviceCount returned 10
-> invalid device ordinal
```

After even more googling, I ran nvidia-smi to get 

```
Unable to determine the device handle for GPU 0000:04:00.0: Unable to communicate with GPU because it is insufficiently powered.
This may be because not all required external power cables are
attached, or the attached cables are not seated properly.
```

I contacted sysadmin and he told me all cables are properly connected, but te problem remained. I tried nvidia-debugdump -l to get 

```

Found 2 NVIDIA devices
    Device ID:              0
    Device name:            NVS 315   (*PrimaryCard)
    GPU internal ID:        GPU-fc8b8a6f-c28f-9860-1469-453ea6a4abb0

Error: nvmlDeviceGetHandleByIndex(): Insufficient External Power
FAILED to get details on GPU (0x1): Insufficient External Power
```

and tried changing driver with update-alternatives --config x86_64-linux-gnu_gl_conf:

```
Selection    Path                                       Priority   Status
------------------------------------------------------------
* 0            /usr/lib/nvidia-352/ld.so.conf              8604      auto mode
  1            /usr/lib/nvidia-352-prime/ld.so.conf        8603      manual mode
  2            /usr/lib/nvidia-352/ld.so.conf              8604      manual mode
  3            /usr/lib/x86_64-linux-gnu/mesa/ld.so.conf   500       manual mode

Press enter to keep the current choice[*], or type selection number: 1
update-alternatives: using /usr/lib/nvidia-352-prime/ld.so.conf to provide /etc/ld.so.conf.d/x86_64-linux-gnu_GL.conf (x86_64-linux-gnu_gl_conf) in manual mode
```

but deviceQuery keeps returning the same error. 

I'd appreciate any suggestions on the matter.

**Comment by shelhamer** [comment]
Sorry, this is a hardware/system configuration issue with CUDA. The problem is not related to Caffe itself.

**Comment by AlexTS1980** [comment]
Thanks Evan, I resolved this particular issue a while ago. The one I'm currently having is why caffe needs to reserve so much vram. For example, semantic segmentation fine-tuning with batch size=1 and img size 1000x600 on Tesla K40 with 12Gb vram is not enough, I need to reduce the size to 500x500,  at which level segmentation quality drops quite a bit (both with FCNs and CRF-RNNs). If you could  recommend anything, it would be greatly appreciated.

**Comment by ferrouswheel** [comment]
@alexts1980 if you remember, can you confirm what the solution was?

**Comment by AlexTS1980** [comment]
for the former, just 

`caffe device_query -gpu [GPU_ID]`

for the latter (memory problem), I didn't find any out-of-the-box solution. I don't know much about memory management at such a deep level, so can't fix it either. The only possible fix I found so far is this: 

`https://github.com/facebook/fb-caffe-exts
`

Though I haven't tried it.

**Comment by ferrouswheel** [comment]
So it turns out I could get this error in the following situation:

- Use a python data layer in Caffe
- In the python data layer, spawn `multiprocessing` Processes to generate data in parallel
- Try to use CUDA from those Processes

I'm unsure of whether their is a CUDA context being shared somehow, but I wouldn't get this error if those Processes instead called an external non-Python command that uses CUDA.

This is very specific to my set up, but wanted to mention it here as googling led me here.

**Comment by mthcom** [comment]
(PyCaffe) I am getting the same issue for running:
`caffe.set_mode_gpu()
caffe.set_device(GPU_ID)`
When GPU_ID is zero there's no problem. But when it's set to 1 or 2 I get the invalid ordinal error.
I should note that in `nvidia-smi` there are 3 registered GPUS

**Comment by mthcom** [comment]
> (PyCaffe) I am getting the same issue for running:
> `caffe.set_mode_gpu()`
> `caffe.set_device(GPU_ID)`
> When GPU_ID is zero there's no problem. But when it's set to 1 or 2 I get the invalid ordinal error.
> I should note that in `nvidia-smi` there are 3 registered GPUS

I was able to solve the issue by using `os.environ["CUDA_VISIBLE_DEVICES"]="1"` in python. Now the only visible GPU is the gpu number 1. Note that you should still use `GPU_ID = 0` but it will run on GPU number 1.
