### ISSUE TITLE
How to make with cuDNN?

### ISSUE THREAD

**Issue by JohnnyY8** [BVLC/caffe#4903]
Hi everyone:
I want to run make command in "py-faster_rcnn/caffe-fast-rcnn" with CUDA-8.0 and cudnn-8.0-linux-x64-v5.1, but got some errors like following:
![image](https://cloud.githubusercontent.com/assets/12611573/19711095/d671739c-9b65-11e6-8e6c-b82b1bcea0c5.png)
I have run these command for copying cudnn files:
cp include/cudnn.h /usr/local/include/
cp lib64/libcudnn.\* /usr/local/lib/
sudo ln -sf /usr/local/lib/libcudnn.so.5.1.3 /usr/local/lib/libcudnn.so.5
sudo ln -sf /usr/local/lib/libcudnn.so.5 /usr/local/lib/libcudnn.so
sudo ldconfig

I do not know how to fix it? Can anyone help me?
Thanks a lot!

**Comment by luckykelfor** [comment]
Have you modified the caffe Makefile.congirue file to suit your situation and built caffe with CUDA8.0 and cuDNNv5.1 successfully? It seems there is a version mismatch problem.

**Comment by JohnnyY8** [comment]
Hi @luckykelfor :
I have solved it, thank you!
