### ISSUE TITLE
 libcudart.so.8.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by fujihuang** [BVLC/caffe#4944]
.......
[==========] 2081 tests from 277 test cases ran. (324463 ms total)
[  PASSED  ] 2081 tests.

i have make runtest,as it is showed above,the runtest have passed.But when i try to run mnist example,the error happened as below:

``:~/caffe$ sudo sh ./examples/mnist/create_mnist.sh
Creating lmdb...
build/examples/mnist/convert_mnist_data.bin: error while loading shared libraries: libcudart.so.8.0: cannot open shared object file: No such file or directory

many people said i should add the path in the bashrc document,and i have added as below:

export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64:$LD_LIBRARY_PATH
export PATH=/usr/local/cuda-8.0/bin:$PATH
export PATH

but i try again,the error happened again.i do not know what i did wrong,if anyone know,please tell me what i should do,thanks in advance.

**Comment by Shubhamcl** [comment]
Hard to understand why is this one closed ? the issue still exists. 

```
.build_release/tools/caffe
.build_release/tools/caffe: error while loading shared libraries: libopenblas.so.0: cannot open shared object file: No such file or directory
Makefile:533: recipe for target 'runtest' failed
make: *** [runtest] Error 127
```

**Comment by Edwardmark** [comment]
I met the same error, please help me

**Comment by zhenni** [comment]
@Edwardmark 

As @fujihuang mentioned, just add the path
`export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64:$LD_LIBRARY_PATH`
`export PATH=/usr/local/cuda-8.0/bin:$PATH`

However, fujihuang adds the third comment  which makes his `PATH` to be empty.

**Comment by Jeonguuz** [comment]
Thank you @Edwardmark . I helped

**Comment by Jeonguuz** [comment]
thank you @zhenni. You saved my day

**Comment by zimenglan-sysu-512** [comment]
hi @zhenni,

your solution does not work. do you have other suggestion how to solve it?

**Comment by SelenaKong** [comment]
sudo ldconfig /usr/local/cuda/lib64 
Fine for me. 
Please refer this link for more information.
https://github.com/tensorflow/tensorflow/issues/5343

**Comment by calf1in1cup** [comment]
if the first method mentioned above can't help,maybe you can try this,
go into the dir /usr/local/cuda/include/host_config.h, then comments"#error-- unsupported GNU version! gcc versions later than 4.9 are not supported!"

**Comment by puneet-kaushal** [comment]
@ghost, I would like to bring some more information to resolve the error as i was also facing the same issue. First of all as zhenni said you need to add the path in the file .bashrc (ubuntu user). For example see the below line I have added in my .bashrc file.
```
LD_LIBRARY_PATH=/usr/local/lib
export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64:${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
```
Please do add one more point once you added these files in the .bashrcm it is important to reflect the changes in the file using the command .bashrc. Now, restart the terminal to see the change. Please run the below command in the terminal

`echo $LD_LIBRARY_PATH`

**You will see the output like this**

`/usr/local/cuda-10.0/lib64::/usr/local/lib
`  
Once, you are successfully in running these steps successfully, please go to the following path

`cd  $HOME/cudnn_samples_v7/mnistCUDNN`

Please run the below command 

`make clean && make`

This command is very important before running the command  ./mnistCUDNN.

You will get the message as shown below

![cuddn_error_resolve](https://user-images.githubusercontent.com/47202519/60499214-a9aa7b00-9cd5-11e9-96fd-4ddc5cafa7fb.png)

With regards
Sanpreet Singh

**Comment by sanpreet** [comment]
@ghost, I would like to bring some more information to resolve the error as i was also facing the same issue. First of all as zhenni said you need to add the path in the file .bashrc (ubuntu user). For example see the below line I have added in my .bashrc file.
```
LD_LIBRARY_PATH=/usr/local/lib
export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64:${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
```
Please do add one more point once you added these files in the .bashrcm it is important to reflect the changes in the file using the command .bashrc. Now, restart the terminal to see the change. Please run the below command in the terminal

`echo $LD_LIBRARY_PATH`

**You will see the output like this**

`/usr/local/cuda-10.0/lib64::/usr/local/lib
`  
Once, you are successfully in running these steps successfully, please go to the following path

`cd  $HOME/cudnn_samples_v7/mnistCUDNN`

Please run the below command 

`make clean && make`

This command is very important before running the command  ./mnistCUDNN.

You will get the message as shown below

![cuddn_error_resolve](https://user-images.githubusercontent.com/47202519/60499214-a9aa7b00-9cd5-11e9-96fd-4ddc5cafa7fb.png)

With regards
Sanpreet Singh

**Comment by LongruiDong** [comment]
> sudo ldconfig /usr/local/cuda/lib64
> Fine for me.
> Please refer this link for more information.
> [tensorflow/tensorflow#5343](https://github.com/tensorflow/tensorflow/issues/5343)

works for me!!
Thanks~~

**Comment by ralyodio** [comment]
how to install on ubuntu 20?
