### ISSUE TITLE
cudnn.hpp:100 Check failed: CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by wlgcqh** [BVLC/caffe#5544]
### Issue summary

F0417 12:45:16.339471 18962 cudnn.hpp:100] Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0) CUDNN_STATUS_BAD_PARAM

### Your system configuration
Operating system:ubuntu 14.04
Compiler:g++ 4.8.4
CUDA version (if applicable):8.0
CUDNN version (if applicable):cudnn8.0-v5.0
BLAS:atlas
Python or MATLAB version (for pycaffe and matcaffe respectively):2.7.10

**Comment by lulu920819** [comment]
I have the same problem, and I change the cudnn version5.0  to 6.0

**Comment by mcian** [comment]
I moved to cuDNN version 6.0 and it works for me too.

**Comment by gittigxuy** [comment]
I have the same question,but I use cuda7.5,and I use cudnn for cuda7.5 which was published in April 2017,so what should I do?

**Comment by captainzone** [comment]
Anyone that has same issue? Welcome to any hints!

GPU: GTX 1080
OS: ubuntu 14.04
cuda, cudnn lib: cuda8.0+cudnn v5,6,7

Error log.
I0824 09:26:10.743613 32391 net.cpp:140] Memory required for data: 14400012
I0824 09:26:10.743626 32391 layer_factory.hpp:77] Creating layer conv1/7x7_s2
I0824 09:26:10.743660 32391 net.cpp:87] Creating Layer conv1/7x7_s2
I0824 09:26:10.743674 32391 net.cpp:409] conv1/7x7_s2 <- data
I0824 09:26:10.743696 32391 net.cpp:383] conv1/7x7_s2 -> conv1/7x7_s2
F0824 09:26:11.183739 32391 cudnn.hpp:100] Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0) CUDNN_STATUS_BAD_PARAM
*** Check failure stack trace: ***
Aborted (core dumped)

I don't have this problem at other gpu card(Titan-X)

**Comment by Mootda** [comment]
I had the same problem, and also changed from cuDNN vers 5.0 to 6.0 and re-make the caffe again with the updated cuDNN

**Comment by Noiredd** [comment]
Fixed by updating cuDNN; also see [related issue](https://github.com/tensorflow/tensorflow/issues/2107#issuecomment-214809325) in TensorFlow repo.
