### ISSUE TITLE
make runtest error----------

### ISSUE THREAD

**Issue by shanYanGuan** [BVLC/caffe#5561]
I can make and make test.But when I make runtest,it show the error below.
**
F0424 17:21:44.405922 130288 cudnn.hpp:108] Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM
*** Check failure stack trace: ***
    @     0x7f157dc4b5cd  google::LogMessage::Fail()
    @     0x7f157dc4d433  google::LogMessage::SendToLog()
    @     0x7f157dc4b15b  google::LogMessage::Flush()
    @     0x7f157dc4de1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f157e30b4c8  caffe::CuDNNConvolutionLayer<>::Reshape()
    @           0x7a9b53  caffe::Layer<>::SetUp()
    @           0x9638ac  caffe::CuDNNConvolutionLayerTest_TestSetupCuDNN_Test<>::TestBody()
    @           0xb97d23  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0xb90aba  testing::Test::Run()
    @           0xb90c08  testing::TestInfo::Run()
    @           0xb90d15  testing::TestCase::Run()
    @           0xb928af  testing::internal::UnitTestImpl::RunAllTests()
    @           0xb92bd3  testing::UnitTest::Run()
    @           0x767b5d  main
    @     0x7f1574f81830  __libc_start_main
    @           0x769449  _start
    @              (nil)  (unknown)

**

 My computer environment:
ubuntu 16.04
cuda 8.0 +cudnn V5.1
gcc 5.4.0
g++ 5.4.0

GPU information；
+----------------------------------------------------------------------------------------------------------+
| NVIDIA-SMI 375.39                                       Driver Version: 375.39                      |
|--------------------------------------------+--------------------------------+----------------------------+
| GPU  Name          Persistence-M| Bus-Id                 Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|              Memory-Usage | GPU-Util  Compute M. |
|========================= +======================+======================|
|   0  Tesla K40c                       Off  | 0000:03:00.0                    Off |                                           0 |
| 49%   74C    P0   136W / 235W   |   4984MiB / 11439MiB            |     98%                     Default |
|   1  Quadro K620                   Off  | 0000:04:00.0                     On |                                      N/A |
| 37%   50C    P8          1W /  30W |   270MiB /  1993MiB               |      3%                      Default |
+-------------------------------------------+----------------------------------------+-------------------------------------+
|   2  Tesla K40c                      Off  | 0000:84:00.0                     Off |                                           0 |
| 60%   75C    P0    134W / 235W |   4770MiB / 11439MiB             |     98%                     Default |
+-------------------------------------------+----------------------------------------+-------------------------------------+

**Comment by shanYanGuan** [comment]
I have tried many method.Still get nothing....

**Comment by bidai541** [comment]
hi shanyan, I get the same error with 375.39 driver and cudnn 5.1 .  Have you solve the problem?

**Comment by bidai541** [comment]
By the way, cuda 8(375.39) + cudnn 6.0 is OK

**Comment by shanYanGuan** [comment]
@bidai541 
cudnn 5.1 you installed is for cuda8.0?
In my station,I found the reason is cudnn's install location was wrong.maybe you can use `mkdir build &&cd build && cmake ..`,and check if cudnn.h  and  cudnn libaray  are the same version.
for example,after I run `cmake ..`,I get the those informations.

> -- CUDA detected: 8.0
> -- Found cuDNN (include: /usr/local/cuda-8.0/include, library: /usr/local/cuda-8.0/lib64/libcudnn.so)

libcudnn.so is link to cudnn.so.5.1.5.

**Comment by bidai541** [comment]
@shanYanGuan  The path of cudnn lib is ok.  
Finally, I compiled the caffe by cudnn v6 and replaced the lib files by cudnn v5.1 to solve this problem.  Besides, anaconda has brought a lot of trouble!!!!

**Comment by shanYanGuan** [comment]
I agree with your opinion!Anaconda recently seems to have some problems....

2017-04-28 10:08 GMT+08:00 bidai541 <notifications@github.com>:

**Comment by h44rd** [comment]
I am getting the same error. I'm using cuda 8 and cudnn 6.
