### ISSUE TITLE
Very strange libcudart.so.7.5 not found problem

### ISSUE THREAD

**Issue by MrWanter** [BVLC/caffe#5818]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary
successfully import caffe with `python -c "import caffe"`, and `ldd path_to_caffe/caffe/_caffe.so | grep libcudart.so.7.5` returns ok. 

But when trying to run a script in terminal with `sudo ./demo.py`, it raises 
`ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory`, 

Have checked `LD_LIBRARY_PATH` with `echo $LD_LIBRARY_PATH`, which returns `/home/cc/Downloads/anaconda/envs/py2/lib:/usr/local/cuda-7.5/lib64:`

I'm using a seperately created env with `python2.7` in `Anaconda`, of which main python is `python 3.6`.

### Steps to reproduce
install `Anaconda` with `python3.6`, create a seperate env with `python2.7`, download and build `caffe`, install `opencv`, then download and build `fast-rcnn`, then run the `demo.py`

### Your system configuration
Operating system: ubuntu 14.04 LTS
Compiler: gcc 4.8.4
CUDA version (if applicable): cuda 7.5
CUDNN version (if applicable): no
BLAS: ATLAS
Python or MATLAB version (for pycaffe and matcaffe respectively):python2.7(which is inside a newly created env in anaconda)

**Comment by MrWanter** [comment]
I tried `sudo ldconfig /usr/local/cuda-7.5/lib64`, the problem disappear, but another similar one came up:
`ImportError: libhdf5_hl.so.10: cannot open shared object file: No such file or directory`
used `find ~/ -type f -name "libhdf5_hl.*"`, returned:
```
/home/cc/Downloads/anaconda/envs/py2/lib/libhdf5_hl.la
/home/cc/Downloads/anaconda/envs/py2/lib/libhdf5_hl.so.10.1.0
/home/cc/Downloads/anaconda/pkgs/hdf5-1.8.17-1/lib/libhdf5_hl.la
/home/cc/Downloads/anaconda/pkgs/hdf5-1.8.17-1/lib/libhdf5_hl.so.10.1.0
/home/cc/Downloads/anaconda/pkgs/hdf5-1.8.17-2/lib/libhdf5_hl.la
/home/cc/Downloads/anaconda/pkgs/hdf5-1.8.17-2/lib/libhdf5_hl.so.10.1.0
/home/cc/Downloads/anaconda/lib/libhdf5_hl.la
/home/cc/Downloads/anaconda/lib/libhdf5_hl.so.10.1.0
```
so I tried `sudo ldconfig /home/cc/Downloads/anaconda/envs/py2/lib`, which returns several pages of similar info as :
```
(py2) cc@cc-Lenovo-Rescuer-14ISK:~/Downloads/fast-rcnn/tools$ sudo ldconfig /home/cc/Downloads/software/envs/py2/lib
/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Test.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5OpenGL.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5QuickWidgets.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5PrintSupport.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5ScriptTools.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Widgets.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5QuickWidgets.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5X11Extras.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Network.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5XmlPatterns.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5XmlPatterns.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Nfc.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Help.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5DesignerComponents.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5DBus.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5MultimediaWidgets.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5WebKit.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libquadmath.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5DBus.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libgomp.so.1.0.0 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Widgets.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Xml.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Qml.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libstdc++.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5WebKitWidgets.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libgcc_s.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5QuickParticles.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5QuickTest.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Multimedia.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5QuickTest.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libgcc_s.so.1 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Concurrent.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Concurrent.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Sql.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Test.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5PrintSupport.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Gui.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Script.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5QuickParticles.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5WebKit.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libiomp5.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Qml.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5DBus.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5WebKitWidgets.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5XcbQpa.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5QuickParticles.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5DesignerComponents.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Script.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Network.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5CLucene.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5ScriptTools.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Bluetooth.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5WebChannel.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5QuickTest.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Qml.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Svg.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libstdc++.so.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5XmlPatterns.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Xml.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Help.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5DBus.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5QuickWidgets.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5WebSockets.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5ScriptTools.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libgfortran.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5X11Extras.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Qml.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Bluetooth.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Nfc.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libgomp.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5PrintSupport.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5MultimediaWidgets.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Nfc.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5XcbQpa.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5X11Extras.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Concurrent.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libgomp.so.1 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Help.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5QuickTest.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5PrintSupport.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Xml.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libgfortran.so.3.0.0 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libquadmath.so.0 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Bluetooth.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Sql.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5ScriptTools.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Multimedia.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Network.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Sql.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Designer.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Multimedia.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5MultimediaWidgets.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Svg.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5WebChannel.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5QuickWidgets.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Widgets.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Concurrent.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Quick.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5OpenGL.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Bluetooth.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5CLucene.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libquadmath.so.0.0.0 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5WebKit.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Test.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Quick.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5QuickParticles.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5WebSockets.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Script.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libstdc++.so.6.0.21 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5WebKitWidgets.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5OpenGL.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5OpenGL.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Sql.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5MultimediaQuick_p.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5X11Extras.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Widgets.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5XcbQpa.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5WebSockets.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Nfc.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5CLucene.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5MultimediaQuick_p.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Gui.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Designer.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5CLucene.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5MultimediaQuick_p.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libgfortran.so.3 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Svg.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5WebKitWidgets.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Xml.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Help.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Multimedia.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5MultimediaWidgets.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5DesignerComponents.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Designer.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5WebKit.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Gui.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Designer.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Network.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Quick.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Gui.so.5 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5WebChannel.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Svg.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Quick.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5WebSockets.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5XcbQpa.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5XmlPatterns.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Script.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5WebChannel.so.5.6 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5DesignerComponents.so 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5Test.so.5.6.2 己被截断

/sbin/ldconfig.real: 文件 /home/cc/Downloads/software/envs/py2/lib/libQt5MultimediaQuick_p.so 己被截断

```

**Comment by MrWanter** [comment]
problem solved, so I typed `dpkg -S libhdf5.so`, which returns:
```
libhdf5-7:amd64: /usr/lib/x86_64-linux-gnu/libhdf5.so.7
libhdf5-dev: /usr/lib/x86_64-linux-gnu/libhdf5.so
libhdf5-7:amd64: /usr/lib/x86_64-linux-gnu/libhdf5.so.7.0.0
```
and I typed `dpkg -S libhdf5_hl.so`, which returns:
```
libhdf5-7:amd64: /usr/lib/x86_64-linux-gnu/libhdf5_hl.so.7.0.0
libhdf5-7:amd64: /usr/lib/x86_64-linux-gnu/libhdf5_hl.so.7
libhdf5-dev: /usr/lib/x86_64-linux-gnu/libhdf5_hl.so
```
so it seems even if I have `libhdf5_hl.so.10.1.0` in `/home/cc/Downloads/anaconda/envs/py2/lib` directory, and `/home/cc/Downloads/anaconda/envs/py2/lib` is in `LD_LIBRARY_PATH`, the system does not recognize it, then I cd to  `/usr/lib/x86_64-linux-gnu` and created links:
```
sudo ln -s libhdf5.so.7 libhdf5.so.10
sudo ln -s libhdf5_hl.so.7 libhdf5_hl.so.10
```
then
 `sudo ldconfig`
then the problem resolved. But note that I linked request for `libhdf5.so.10` to `libhdf5.so.7`, would this gives   some version mismatch problem? I'm not sure, but the script `demo.py `runs properly.

**Comment by Noiredd** [comment]
I suggest doing `make runtest` to make sure the HDF5 support runs well.  
In case of further issues, please post to the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users).
