### ISSUE TITLE
warning message when compile

### ISSUE THREAD

**Issue by yixuan178** [BVLC/caffe#6381]
src/caffe/CMakeFiles/cuda_compile.dir/solvers/cuda_compile_generated_rmsprop_solver.cu.o
/opt/caffe/include/caffe/util/cudnn.hpp: In function 'const char* cudnnGetErrorString(cudnnStatus_t)':
/opt/caffe/include/caffe/util/cudnn.hpp:21:8: warning: enumeration value 'CUDNN_STATUS_RUNTIME_IN_PROGRESS' not handled in switch [-Wswitch]
   switch (status) {
        ^
/opt/caffe/include/caffe/util/cudnn.hpp:21:8: warning: enumeration value 'CUDNN_STATUS_RUNTIME_FP_OVERFLOW' not handled in switch [-Wswitch]
/opt/caffe/include/caffe/util/cudnn.hpp: In function 'const char* cudnnGetErrorString(cudnnStatus_t)':
/opt/caffe/include/caffe/util/cudnn.hpp:21:8: warning: enumeration value 'CUDNN_STATUS_RUNTIME_IN_PROGRESS' not handled in switch [-Wswitch]
   switch (status) {

It should be caused by lack of default branch when using switch. is it possible to add to prevent warning message?

**Comment by amylmy** [comment]
update the cudnn.hpp in caffe/include/caffe/util/cudnn.hpp works for me.
here is the link: 
https://github.com/BVLC/caffe/blob/master/include/caffe/util/cudnn.hpp

**Comment by sziraqui** [comment]
This cause build to fail with cudnn 7.1.4 on Nvidia 940m having compute capability 5.0
Here's the start of the error
```
NVCC src/caffe/solvers/adadelta_solver.cu
nvcc fatal   : Unsupported gpu architecture 'compute_20'
```

**Comment by Noiredd** [comment]
This has been discussed in #5793 - most likely your Caffe is not the latest version (and does not support whatever cuDNN you might have).
