### ISSUE TITLE
Caffe doesn't work on Tesla V100 GPUs.

### ISSUE THREAD

**Issue by BinZlP** [BVLC/caffe#6809]
### Issue summary
Caffe doesn't work well on Tesla V100.

This is my error message:
**check failed error == cudasuccess no kernel image is available for execution on the device.
Stack trace:**

### Steps to reproduce
Install OpenPose by CMake-GUI(as installing OpenPose, CMake also build Caffe as well).
Execute example codes.

### Tried solutions
Give manual number for CUDA_ARCH of CMake Flag.

### System configuration

* Operating system: Ubuntu 16.04
* Compiler: CUDA
* CUDA version (if applicable): 10.0
* CUDNN version (if applicable): 7.5
* BLAS: 
* Python version (if using pycaffe): 3.5.1
* MATLAB version (if using matcaffe): 
+ GPU: Nvidia Tesla V100 32GB * 2

### Issue checklist

- [x] read the guidelines and removed the first paragraph
- [x] written a short summary and detailed steps to reproduce
- [x] explained how solutions to related problems failed (tick if found none)
- [x] filled system configuration
- [x] attached relevant logs/config files (tick if not applicable)

**Comment by BinZlP** [comment]
I solved it by updating Cuda.cmake file's known_gpu_archs.

**Comment by Luckick** [comment]
Hi,

do you mean:
set(Caffe_known_gpu_archs "30 35 50 52 60 61 70 75")
?

I found it is already set this way, include 70 for V100. But still fails.

Thanks.
