### ISSUE TITLE
CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by ssshcj** [BVLC/caffe#6873]
Compile Caffe with cuDnn get an error:    cudnn_deconv_layer.cpp:53] Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR
my cuda driver version is 10.2(430) runtime version is 10.1 and cuDnn version is 7.6.4

Can someone help me? Thanks very much!!!

**Comment by pjyazdian** [comment]
If you have tried too much stuff and you still don't deal it, try " sudo rm -rf ~/.nv/"
It worked for me.

**Comment by yuxwind** [comment]
Actually, I was out of GPU memory. After killing some application, the error is fixed.
